### ISSUE TITLE
Nome do repositório

### ISSUE THREAD

**Issue by lucaslopes** [uvacomprj/uvacomprj.github.io#3]
Sugiro renomear de `uvacomprj.github.io` para `website` ou simplesmente `site`.

**Comment by flisboac** [comment]
Oi, @lucaslopes.

O nome do repositório é proposital, pois é por este padrão de nome que ele passa a servir como o Pages da organização `uvacomprj`. Este é o "landing page" do grupo. Assim, a URL fica apenas `https://uvacomprj.github.io`, e não `https://uvacomprj.github.io/site` (caso tivéssemos um repositório em `https://github.com/uvacomprj/site`).

Depois verifico se é possível configurar o Pages para a organização com um nome diferente (talvez seja).
